### ISSUE TITLE
linker failure during `scons refu`

### ISSUE THREAD

**Issue by pirapira** [LefterisJP/refulang#1]
I saw a linking failure during `scons refu`.
```
g++ -L/usr/lib/llvm-3.7/lib -o core/refu <snip> -lz <snip> -lLLVM<snip>
<snip>: undefined reference to `compressBound'
```
The reason was `-lz` option came after `-lLLVM` options.

I solved this problem; in `core/SConstruct`, I moved `local_env.Append(LIBS=['dl', 'z', 'ncurses'])`  4 lines downward.

**Comment by LefterisJP** [comment]
Thanks Yoichi. Can you open a PR for this in the actual refu core repo? https://github.com/LefterisJP/refulangcore

The refulang github project is like an umbrella project for the 3 repos that make up refulang.

**Comment by pirapira** [comment]
Created https://github.com/LefterisJP/refulangcore/pull/1.

**Comment by LefterisJP** [comment]
Closing this since it's move to refulang core repo.
